# -*- coding: utf-8 -*-
"""Untitled107.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e5NBUAUD-PuAUVEKm_dgujze1sqRePeg
"""

import pandas as pd

df = pd.read_csv(
    "open-meteo-32.30N35.78E770m.csv",
    skiprows=6
)

df.head()

import pandas as pd

df = pd.read_csv(
    "open-meteo-32.30N35.78E770m.csv",
    skiprows=3
)

print(df.columns.tolist())
print(df.shape)
df.head()

print("Missing values:")
print(df.isnull().sum())

print("\nStatistics:")
print(df.describe())

cold_hours = df[df["temperature_2m (°C)"] <= 0]

print("Hours with temperature <= 0°C:", len(cold_hours))

cold_hours.head(10)

cold_hours[
    [
        "time",
        "temperature_2m (°C)",
        "relative_humidity_2m (%)",
        "dew_point_2m (°C)",
        "precipitation (mm)",
        "cloud_cover (%)",
        "wind_speed_10m (km/h)"
    ]
].head(20)

cold_hours[
    [
        "temperature_2m (°C)",
        "relative_humidity_2m (%)",
        "dew_point_2m (°C)",
        "cloud_cover (%)",
        "wind_speed_10m (km/h)"
    ]
].describe()

# Convert time to datetime
df["time"] = pd.to_datetime(df["time"])

# Minimum temperature during the NEXT 3 hours
df["future_min_temp_3h"] = df[
    [
        "temperature_2m (°C)"
    ]
].shift(-1)

df["future_min_temp_3h"] = pd.concat([
    df["temperature_2m (°C)"].shift(-1),
    df["temperature_2m (°C)"].shift(-2),
    df["temperature_2m (°C)"].shift(-3)
], axis=1).min(axis=1)

# Frost target
df["frost"] = (df["future_min_temp_3h"] <= 0).astype(int)

df[[
    "time",
    "temperature_2m (°C)",
    "dew_point_2m (°C)",
    "future_min_temp_3h",
    "frost"
]].head(10)

# Remove rows without a complete 3-hour future window
df = df.dropna(subset=["future_min_temp_3h"]).copy()

print("Dataset shape:", df.shape)
print("\nFrost distribution:")
print(df["frost"].value_counts())

print("\nFrost percentage:")
print(df["frost"].value_counts(normalize=True) * 100)

features = [
    "temperature_2m (°C)",
    "relative_humidity_2m (%)",
    "dew_point_2m (°C)",
    "precipitation (mm)",
    "cloud_cover (%)",
    "wind_speed_10m (km/h)"
]

X = df[features]
y = df["frost"]

print("X shape:", X.shape)
print("y shape:", y.shape)
print("\nTarget distribution:")
print(y.value_counts())

# Time-based split: 80% for training, 20% for testing

split_index = int(len(df) * 0.8)

X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]

y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

print("\nTraining target:")
print(y_train.value_counts())

print("\nTesting target:")
print(y_test.value_counts())

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Classification Report:")
print(classification_report(y_test, y_pred, digits=4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

import pandas as pd

feature_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": model.feature_importances_
}).sort_values("Importance", ascending=False)

print(feature_importance)

from sklearn.metrics import classification_report, confusion_matrix

# Probability of Frost
frost_probability = model.predict_proba(X_test)[:, 1]

# Try a lower threshold
threshold = 0.30

y_pred_30 = (frost_probability >= threshold).astype(int)

print("Threshold:", threshold)
print("\nClassification Report:")
print(classification_report(y_test, y_pred_30, digits=4))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_30))

from sklearn.metrics import precision_score, recall_score, f1_score

thresholds = [0.50, 0.40, 0.30, 0.20, 0.10]

results = []

for threshold in thresholds:
    predictions = (frost_probability >= threshold).astype(int)

    results.append({
        "Threshold": threshold,
        "Precision": precision_score(y_test, predictions, zero_division=0),
        "Recall": recall_score(y_test, predictions, zero_division=0),
        "F1": f1_score(y_test, predictions, zero_division=0)
    })

threshold_results = pd.DataFrame(results)

print(threshold_results)

import joblib

joblib.dump(model, "frost_random_forest.pkl")

print("Model saved successfully!")

model_info = {
    "features": features,
    "threshold": 0.20
}

joblib.dump(model_info, "frost_model_info.pkl")

print("Model information saved successfully!")

import requests
import pandas as pd

def get_weather(latitude, longitude):
    url = "https://api.open-meteo.com/v1/forecast"

    params = {
        "latitude": latitude,
        "longitude": longitude,
        "hourly": [
            "temperature_2m",
            "relative_humidity_2m",
            "dew_point_2m",
            "precipitation",
            "cloud_cover",
            "wind_speed_10m"
        ],
        "timezone": "Asia/Amman",
        "forecast_days": 3
    }

    response = requests.get(url, params=params)
    response.raise_for_status()

    data = response.json()

    weather = pd.DataFrame(data["hourly"])

    return weather


# Example: Amman
weather = get_weather(31.95, 35.91)

weather.head()

# Rename Open-Meteo columns to the exact names used during training

weather_ml = weather.rename(columns={
    "temperature_2m": "temperature_2m (°C)",
    "relative_humidity_2m": "relative_humidity_2m (%)",
    "dew_point_2m": "dew_point_2m (°C)",
    "precipitation": "precipitation (mm)",
    "cloud_cover": "cloud_cover (%)",
    "wind_speed_10m": "wind_speed_10m (km/h)"
}).copy()

# Exact training features
features = [
    "temperature_2m (°C)",
    "relative_humidity_2m (%)",
    "dew_point_2m (°C)",
    "precipitation (mm)",
    "cloud_cover (%)",
    "wind_speed_10m (km/h)"
]

# Frost probability
weather_ml["frost_probability"] = model.predict_proba(
    weather_ml[features]
)[:, 1]

# Alert threshold
threshold = 0.20

weather_ml["frost_risk"] = (
    weather_ml["frost_probability"] >= threshold
).astype(int)

weather_ml[
    [
        "time",
        "temperature_2m (°C)",
        "dew_point_2m (°C)",
        "frost_probability",
        "frost_risk"
    ]
].head(24)

# Find the hours with the highest frost probability

risk_check = weather_ml[
    [
        "time",
        "temperature_2m (°C)",
        "dew_point_2m (°C)",
        "frost_probability",
        "frost_risk"
    ]
].copy()

risk_check = risk_check.sort_values(
    "frost_probability",
    ascending=False
)

print("Highest frost-risk hours:")
display(risk_check.head(10))

print("\nMinimum temperature:")
print(weather_ml["temperature_2m (°C)"].min())

print("\nMaximum frost probability:")
print(weather_ml["frost_probability"].max())

pd.set_option("display.float_format", "{:.6f}".format)

risk_check = weather_ml[
    [
        "time",
        "temperature_2m (°C)",
        "dew_point_2m (°C)",
        "frost_probability",
        "frost_risk"
    ]
].copy()

risk_check = risk_check.sort_values(
    "frost_probability",
    ascending=False
)

display(risk_check.head(10))

print("Maximum frost probability:",
      weather_ml["frost_probability"].max())

# Test the model with a cold-weather scenario

cold_test = pd.DataFrame({
    "temperature_2m (°C)": [-2.0],
    "relative_humidity_2m (%)": [90],
    "dew_point_2m (°C)": [-4.0],
    "precipitation (mm)": [0.0],
    "cloud_cover (%)": [10],
    "wind_speed_10m (km/h)": [3.0]
})

cold_probability = model.predict_proba(cold_test)[:, 1][0]

print("Cold-weather test")
print("Frost probability:", cold_probability)
print("Frost probability %:", f"{cold_probability:.2%}")

if cold_probability >= 0.20:
    print("🔴 HIGH FROST RISK")
elif cold_probability >= 0.10:
    print("🟡 MODERATE FROST RISK")
else:
    print("🟢 LOW FROST RISK")

# Frost risk summary for the current forecast

summary = {
    "Minimum Temperature (°C)": weather_ml["temperature_2m (°C)"].min(),
    "Maximum Temperature (°C)": weather_ml["temperature_2m (°C)"].max(),
    "Maximum Frost Probability (%)": weather_ml["frost_probability"].max() * 100,
    "High Risk Hours": (weather_ml["frost_risk"] == 1).sum()
}

for key, value in summary.items():
    print(f"{key}: {value:.2f}")

import matplotlib.pyplot as plt

labels = [
    "Min Temp (°C)",
    "Max Temp (°C)",
    "Max Frost Probability (%)",
    "High Risk Hours"
]

values = [
    weather_ml["temperature_2m (°C)"].min(),
    weather_ml["temperature_2m (°C)"].max(),
    weather_ml["frost_probability"].max() * 100,
    (weather_ml["frost_risk"] == 1).sum()
]

plt.figure(figsize=(10, 5))
bars = plt.bar(labels, values)

plt.title("Frost Risk Summary - Amman")
plt.ylabel("Value")
plt.xticks(rotation=20)

for bar, value in zip(bars, values):
    plt.text(
        bar.get_x() + bar.get_width()/2,
        bar.get_height(),
        f"{value:.2f}",
        ha="center",
        va="bottom"
    )

plt.tight_layout()
plt.show()

final_result = weather_ml[
    [
        "time",
        "temperature_2m (°C)",
        "relative_humidity_2m (%)",
        "dew_point_2m (°C)",
        "frost_probability",
        "frost_risk"
    ]
].copy()

final_result["frost_probability (%)"] = (
    final_result["frost_probability"] * 100
).round(2)

final_result["risk_level"] = final_result["frost_probability (%)"].apply(
    lambda x: "HIGH" if x >= 20 else
              "MODERATE" if x >= 10 else
              "LOW"
)

final_result.head(24)

# Save final prediction results

final_result.to_csv("frost_prediction_results.csv", index=False)

print("Final results saved successfully!")
print("Rows:", len(final_result))

import matplotlib.pyplot as plt

# Dashboard summary
min_temp = weather_ml["temperature_2m (°C)"].min()
max_temp = weather_ml["temperature_2m (°C)"].max()
max_probability = weather_ml["frost_probability"].max() * 100
risk_hours = (weather_ml["frost_risk"] == 1).sum()

print("=" * 50)
print("       FROST RISK DASHBOARD - AMMAN")
print("=" * 50)

print(f"Minimum Temperature: {min_temp:.1f} °C")
print(f"Maximum Temperature: {max_temp:.1f} °C")
print(f"Maximum Frost Probability: {max_probability:.1f}%")
print(f"High Frost Risk Hours: {risk_hours}")

if max_probability >= 20:
    print("Risk Level: HIGH")
elif max_probability >= 10:
    print("Risk Level: MODERATE")
else:
    print("Risk Level: LOW")

print("=" * 50)

plt.figure(figsize=(10, 5))

labels = [
    "Min Temp",
    "Max Temp",
    "Frost Probability",
    "High Risk Hours"
]

values = [
    min_temp,
    max_temp,
    max_probability,
    risk_hours
]

bars = plt.bar(labels, values)

plt.title("Frost Risk Dashboard - Amman")
plt.ylabel("Value")

for bar, value in zip(bars, values):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        f"{value:.1f}",
        ha="center",
        va="bottom"
    )

plt.tight_layout()

plt.savefig("frost_risk_dashboard.png", dpi=300, bbox_inches="tight")

plt.show()

print("Dashboard saved successfully!")

def check_frost_risk(latitude, longitude):

    # Get weather data
    weather = get_weather(latitude, longitude)

    # Rename API columns to the exact names used during model training
    weather = weather.rename(columns={
        "temperature_2m": "temperature_2m (°C)",
        "relative_humidity_2m": "relative_humidity_2m (%)",
        "dew_point_2m": "dew_point_2m (°C)",
        "precipitation": "precipitation (mm)",
        "cloud_cover": "cloud_cover (%)",
        "wind_speed_10m": "wind_speed_10m (km/h)"
    })

    # Predict frost probability
    weather["frost_probability"] = model.predict_proba(
        weather[features]
    )[:, 1]

    # Maximum probability and minimum temperature
    max_probability = weather["frost_probability"].max()
    min_temperature = weather["temperature_2m (°C)"].min()

    # Risk level
    if max_probability >= 0.20:
        risk = "HIGH"
        message = "🔴 تحذير! يوجد خطر مرتفع من الصقيع."
    elif max_probability >= 0.10:
        risk = "MODERATE"
        message = "🟡 تنبيه! يوجد احتمال متوسط للصقيع."
    else:
        risk = "LOW"
        message = "🟢 لا يوجد خطر مرتفع من الصقيع."

    print("=" * 50)
    print("🌱 FROST RISK ALERT")
    print("=" * 50)
    print(f"📍 Location: {latitude}, {longitude}")
    print(f"🌡️ Minimum Temperature: {min_temperature:.1f} °C")
    print(f"❄️ Frost Probability: {max_probability:.1%}")
    print(f"⚠️ Risk Level: {risk}")
    print()
    print(message)
    print("=" * 50)

    return weather

weather_amman = check_frost_risk(31.95, 35.91)

# ==========================================
# 🇯🇴 Jordan Frost Early Warning System
# ==========================================

jordan_locations = {
    "عمّان": {
        "عمّان": (31.9539, 35.9106),
        "ناعور": (31.8667, 35.8167),
        "صويلح": (32.0167, 35.8500),
        "وادي السير": (31.9500, 35.8000)
    },

    "الزرقاء": {
        "الزرقاء": (32.0728, 36.0880)
    },

    "إربد": {
        "إربد": (32.5556, 35.8500),
        "الرمثا": (32.5589, 36.0080)
    },

    "جرش": {
        "جرش": (32.2746, 35.8961)
    },

    "عجلون": {
        "عجلون": (32.3336, 35.7528)
    },

    "المفرق": {
        "المفرق": (32.3429, 36.2080)
    },

    "السلط": {
        "السلط": (32.0392, 35.7272)
    },

    "مادبا": {
        "مادبا": (31.7167, 35.8000)
    },

    "الكرك": {
        "الكرك": (31.1853, 35.7047)
    },

    "الطفيلة": {
        "الطفيلة": (30.8375, 35.6044)
    },

    "معان": {
        "معان": (30.1962, 35.7345)
    },

    "العقبة": {
        "العقبة": (29.5321, 35.0063)
    }
}


# ==========================================
# اختيار المحافظة
# ==========================================

print("=" * 60)
print("🇯🇴 نظام الإنذار المبكر لخطر الصقيع")
print("=" * 60)

governorates = list(jordan_locations.keys())

for i, governorate in enumerate(governorates, 1):
    print(f"{i}. {governorate}")

choice = int(input("\n📍 اختر رقم المحافظة: "))

governorate = governorates[choice - 1]

# ==========================================
# اختيار المنطقة
# ==========================================

areas = list(jordan_locations[governorate].keys())

print(f"\n📍 مناطق {governorate}:")

for i, area in enumerate(areas, 1):
    print(f"{i}. {area}")

area_choice = int(input("\n📍 اختر رقم المنطقة: "))

area = areas[area_choice - 1]

latitude, longitude = jordan_locations[governorate][area]

print("\n⏳ جاري تحليل حالة الطقس...")
print(f"📍 الموقع: {area} - {governorate}")

# ==========================================
# 🔍 Frost Risk Prediction - Jordan
# ==========================================

weather_result = check_frost_risk(latitude, longitude)

# Get values from returned weather dataframe
min_temperature = weather_result["temperature_2m (°C)"].min()
max_frost_probability = weather_result["frost_probability"].max()

# Convert probability to percentage
frost_probability_percent = max_frost_probability * 100

# Determine risk level
if frost_probability_percent >= 20:
    risk_level = "HIGH"
elif frost_probability_percent >= 10:
    risk_level = "MODERATE"
else:
    risk_level = "LOW"


# ==========================================
# 📢 Citizen Alert
# ==========================================

print("\n" + "=" * 60)
print("🌱 FROST RISK ALERT")
print("=" * 60)

print(f"📍 المحافظة: {governorate}")
print(f"📍 المنطقة: {area}")

print(f"🌡️ أقل درجة حرارة متوقعة: {min_temperature:.1f} °C")
print(f"❄️ احتمال الصقيع: {frost_probability_percent:.1f}%")
print(f"⚠️ مستوى الخطر: {risk_level}")

print("-" * 60)

if risk_level == "HIGH":

    print("🔴 تحذير: خطر مرتفع للصقيع")
    print("⚠️ يوجد احتمال مرتفع لحدوث الصقيع.")
    print("🌱 يُنصح باتخاذ الإجراءات الوقائية لحماية المحاصيل.")

elif risk_level == "MODERATE":

    print("🟡 تنبيه: خطر متوسط للصقيع")
    print("⚠️ توجد احتمالية لحدوث الصقيع.")
    print("🌱 يُنصح بمتابعة حالة الطقس واتخاذ الاحتياطات.")

else:

    print("🟢 خطر منخفض للصقيع")
    print("✅ لا يوجد خطر مرتفع من الصقيع في الموقع المحدد.")

print("=" * 60)

!pip -q install gradio

import gradio as gr

# ==========================================
# 🇯🇴 Jordan Frost Alert
# Interactive Citizen Interface
# ==========================================

def predict_frost(governorate, area):

    latitude, longitude = jordan_locations[governorate][area]

    # Get weather + prediction
    weather_result = check_frost_risk(latitude, longitude)

    # Minimum temperature
    min_temperature = weather_result["temperature_2m (°C)"].min()

    # Maximum frost probability
    frost_probability = weather_result["frost_probability"].max()
    probability_percent = frost_probability * 100

    # Risk level
    if probability_percent >= 20:
        risk_level = "🔴 HIGH"
        message = (
            "تحذير: يوجد احتمال مرتفع للصقيع في منطقتك. "
            "إذا كنت مزارعًا، يُنصح باتخاذ الإجراءات الوقائية المناسبة."
        )

    elif probability_percent >= 10:
        risk_level = "🟡 MODERATE"
        message = (
            "تنبيه: توجد احتمالية متوسطة للصقيع. "
            "ننصح بمتابعة حالة الطقس واتخاذ الاحتياطات المناسبة."
        )

    else:
        risk_level = "🟢 LOW"
        message = (
            "لا يوجد خطر مرتفع للصقيع في الموقع المحدد."
        )

    result = f"""
# 🌱 تنبيه خطر الصقيع

### 📍 الموقع
**{area} - {governorate}**

### 🌡️ أقل درجة حرارة متوقعة
**{min_temperature:.1f} °C**

### ❄️ احتمال الصقيع
**{probability_percent:.1f}%**

### ⚠️ مستوى الخطر
**{risk_level}**

---

### 📢 التنبيه

{message}

---

*النظام يقدم توقعًا مساعدًا اعتمادًا على بيانات الطقس والنموذج المدرب.*
"""

    return result


# Update areas when governorate changes
def update_areas(governorate):

    areas = list(jordan_locations[governorate].keys())

    return gr.update(
        choices=areas,
        value=areas[0]
    )


# ==========================================
# Interface
# ==========================================

with gr.Blocks(title="Jordan Frost Alert") as app:

    gr.Markdown("""
    # 🇯🇴 Jordan Frost Alert
    ## 🌱 نظام الإنذار المبكر لخطر الصقيع

    **اختر موقعك في الأردن لمعرفة مستوى خطر الصقيع المتوقع.**
    """)

    with gr.Row():

        governorate = gr.Dropdown(
            choices=list(jordan_locations.keys()),
            value="عمّان",
            label="📍 المحافظة"
        )

        area = gr.Dropdown(
            choices=list(jordan_locations["عمّان"].keys()),
            value="عمّان",
            label="📍 المنطقة"
        )

    check_button = gr.Button(
        "🔍 افحص خطر الصقيع",
        variant="primary"
    )

    result = gr.Markdown()

    governorate.change(
        update_areas,
        inputs=governorate,
        outputs=area
    )

    check_button.click(
        predict_frost,
        inputs=[governorate, area],
        outputs=result
    )


app.launch(share=True)

import gradio as gr


# ==========================================================
# 🇯🇴 Jordan Locations
# ==========================================================

jordan_locations = {

    "عمّان": {
        "عمّان": (31.9539, 35.9106),
        "ماركا": (31.9833, 35.9833),
        "الجبيهة": (32.0167, 35.8833),
        "صويلح": (31.9833, 35.8333),
        "ناعور": (31.8667, 35.8167)
    },

    "إربد": {
        "إربد": (32.5556, 35.8500),
        "الرمثا": (32.5589, 36.0069),
        "الحصن": (32.4917, 35.8833),
        "بني عبيد": (32.5069, 35.7944)
    },

    "الزرقاء": {
        "الزرقاء": (32.0728, 36.0880),
        "الرصيفة": (32.0178, 36.0464),
        "الهاشمية": (32.1400, 36.0800)
    },

    "البلقاء": {
        "السلط": (32.0392, 35.7272),
        "الفحيص": (32.0000, 35.7833),
        "عين الباشا": (32.0833, 35.7500),
        "دير علا": (32.1833, 35.6000)
    },

    "مادبا": {
        "مادبا": (31.7167, 35.7939),
        "ذيبان": (31.5000, 35.7667),
        "ماعين": (31.6833, 35.7333)
    },

    "جرش": {
        "جرش": (32.2747, 35.8961),
        "برما": (32.3000, 35.7833),
        "سوف": (32.3667, 35.8833)
    },

    "عجلون": {
        "عجلون": (32.3333, 35.7500),
        "كفرنجة": (32.2667, 35.7500),
        "عنجرة": (32.2833, 35.7167)
    },

    "المفرق": {
        "المفرق": (32.3414, 36.2078),
        "رحاب": (32.2833, 36.1000),
        "البادية الشمالية": (32.4000, 36.3000)
    },

    "الكرك": {
        "الكرك": (31.1853, 35.7047),
        "المزار الجنوبي": (31.0667, 35.7000),
        "مؤتة": (31.0833, 35.7000)
    },

    "الطفيلة": {
        "الطفيلة": (30.8375, 35.6044),
        "بصيرا": (30.7333, 35.6167),
        "الحسا": (30.7833, 35.7500)
    },

    "معان": {
        "معان": (30.1962, 35.7345),
        "الشوبك": (30.5167, 35.5667),
        "وادي موسى": (30.3200, 35.4800)
    },

    "العقبة": {
        "العقبة": (29.5267, 35.0078),
        "وادي عربة": (29.8000, 35.1500),
        "الديسة": (29.6000, 35.4500)
    }
}


# ==========================================================
# 🌱 Crop Types
# ==========================================================

crop_types = {

    "🥬 خضروات ورقية": {
        "name": "الخضروات الورقية",
        "advice": "يُنصح بمتابعة درجات الحرارة خلال ساعات الليل والصباح الباكر، والانتباه للمحاصيل الحساسة للبرد."
    },

    "🍅 خضروات مثمرة": {
        "name": "الخضروات المثمرة",
        "advice": "يُنصح بمتابعة انخفاض درجات الحرارة واتخاذ إجراءات الحماية المناسبة عند ارتفاع خطر الصقيع."
    },

    "🍊 أشجار مثمرة": {
        "name": "الأشجار المثمرة",
        "advice": "يُنصح بمراقبة فترة الصقيع المتوقعة والانتباه بشكل خاص خلال ساعات الليل والصباح الباكر."
    },

    "🌾 محاصيل حقلية": {
        "name": "المحاصيل الحقلية",
        "advice": "يُنصح بمتابعة التوقعات الجوية وتقييم حساسية المحصول للبرد قبل اتخاذ أي إجراء."
    },

    "🌿 أعشاب ونباتات": {
        "name": "الأعشاب والنباتات",
        "advice": "يُنصح بمتابعة درجات الحرارة وحماية النباتات الحساسة عند ارتفاع مستوى الخطر."
    }
}


# ==========================================================
# 🔮 Frost Prediction
# ==========================================================

def predict_frost_final(governorate, area, crop):

    try:

        # --------------------------------------------------
        # Get coordinates
        # --------------------------------------------------

        latitude, longitude = jordan_locations[
            governorate
        ][area]


        # --------------------------------------------------
        # Crop information
        # --------------------------------------------------

        crop_info = crop_types[crop]

        crop_name = crop_info["name"]

        crop_advice = crop_info["advice"]


        # --------------------------------------------------
        # Weather + prediction
        # --------------------------------------------------

        weather_result = check_frost_risk(
            latitude,
            longitude
        ).copy()


        # --------------------------------------------------
        # Minimum temperature
        # --------------------------------------------------

        min_temperature = weather_result[
            "temperature_2m (°C)"
        ].min()


        # --------------------------------------------------
        # Frost probability
        # --------------------------------------------------

        frost_probability = weather_result[
            "frost_probability"
        ].max()

        probability_percent = frost_probability * 100


        # ==================================================
        # Risk Classification
        # ==================================================

        if probability_percent >= 20:

            level = "🔴 خطر مرتفع"

            color = "#dc2626"

            background = "#fee2e2"

            recommendation = f"""

            <b>🚨 توصيات للمزارع</b>

            <p>
                <b>🌱 المحصول:</b>
                {crop_name}
            </p>

            <ul>

                <li>
                    توجد احتمالية مرتفعة للصقيع.
                </li>

                <li>
                    يُنصح باتخاذ الإجراءات الوقائية
                    المناسبة لحماية المحصول.
                </li>

                <li>
                    الانتباه بشكل خاص خلال ساعات الخطر
                    المحددة في التوقعات.
                </li>

                <li>
                    {crop_advice}
                </li>

            </ul>

            """


        elif probability_percent >= 10:

            level = "🟡 خطر متوسط"

            color = "#d97706"

            background = "#fef3c7"

            recommendation = f"""

            <b>⚠️ توصيات للمزارع</b>

            <p>
                <b>🌱 المحصول:</b>
                {crop_name}
            </p>

            <ul>

                <li>
                    توجد احتمالية متوسطة للصقيع.
                </li>

                <li>
                    يُنصح بالاستعداد ومتابعة درجات الحرارة
                    خلال الليل والصباح الباكر.
                </li>

                <li>
                    إعادة فحص الموقع إذا انخفضت
                    درجات الحرارة.
                </li>

                <li>
                    {crop_advice}
                </li>

            </ul>

            """


        else:

            level = "🟢 خطر منخفض"

            color = "#16a34a"

            background = "#dcfce7"

            recommendation = f"""

            <b>✅ الحالة الحالية مطمئنة</b>

            <p>
                <b>🌱 المحصول:</b>
                {crop_name}
            </p>

            <ul>

                <li>
                    لا يوجد خطر مرتفع للصقيع حاليًا
                    في الموقع المحدد.
                </li>

                <li>
                    يُنصح بالاستمرار في متابعة
                    التحديثات الجوية.
                </li>

                <li>
                    يمكن إعادة الفحص عند تغير
                    حالة الطقس.
                </li>

                <li>
                    {crop_advice}
                </li>

            </ul>

            """


        # ==================================================
        # Risk Hours
        # ==================================================

        risk_hours = weather_result[
            weather_result["frost_probability"] >= 0.20
        ]


        if len(risk_hours) > 0:

            first_risk = risk_hours[
                "time"
            ].iloc[0]

            last_risk = risk_hours[
                "time"
            ].iloc[-1]

            risk_period = (
                f"من {first_risk} إلى {last_risk}"
            )

        else:

            risk_period = (
                "لا توجد ساعات ذات خطر مرتفع حاليًا."
            )


        # ==================================================
        # Next 6 Hours
        # ==================================================

        next_hours = weather_result.head(6)

        hours_html = ""


        for _, row in next_hours.iterrows():

            temp = row[
                "temperature_2m (°C)"
            ]

            probability = (
                row["frost_probability"] * 100
            )

            time = row["time"]


            if probability >= 20:

                status = "🔴 مرتفع"

            elif probability >= 10:

                status = "🟡 متوسط"

            else:

                status = "🟢 منخفض"


            hours_html += f"""

            <tr>

                <td class="forecast-cell">
                    {time}
                </td>

                <td class="forecast-cell">
                    {temp:.1f} °C
                </td>

                <td class="forecast-cell">
                    {probability:.1f}%
                </td>

                <td class="forecast-cell">
                    {status}
                </td>

            </tr>

            """


        # ==================================================
        # Final Result
        # ==================================================

        return f"""

        <div class="result-card">


            <h2 class="result-title">

                🌱 نتيجة فحص خطر الصقيع

            </h2>


            <hr class="green-line">


            <!-- Location -->

            <div class="info-section">

                <div class="info-label">
                    📍 الموقع
                </div>

                <div class="info-value">
                    {governorate} - {area}
                </div>

            </div>


            <!-- Crop -->

            <div class="info-section">

                <div class="info-label">
                    🌱 نوع المحصول
                </div>

                <div class="info-value crop-value">
                    {crop_name}
                </div>

            </div>


            <!-- Temperature -->

            <div class="info-section">

                <div class="info-label">
                    🌡️ أقل درجة حرارة متوقعة
                </div>

                <div class="temperature-value">
                    {min_temperature:.1f} °C
                </div>

            </div>


            <!-- Probability -->

            <div class="info-section">

                <div class="info-label">
                    ❄️ احتمال الصقيع
                </div>

                <div class="temperature-value">
                    {probability_percent:.1f}%
                </div>

            </div>


            <!-- Risk -->

            <div class="info-section">

                <div class="info-label">
                    ⚠️ مستوى الخطر
                </div>

                <div
                    class="risk-badge"
                    style="
                        color:{color};
                        background:{background};
                        border-color:{color};
                    "
                >

                    {level}

                </div>

            </div>


            <!-- Risk Period -->

            <div class="info-section">

                <div class="info-label">
                    🕐 فترة الخطر
                </div>

                <div class="risk-period">
                    {risk_period}
                </div>

            </div>


            <!-- Recommendations -->

            <div
                class="recommendation"
                style="
                    background:{background};
                "
            >

                {recommendation}

            </div>


            <!-- Forecast -->

            <div class="forecast-section">


                <h3 class="forecast-title">

                    🌤️ توقعات الساعات القادمة

                </h3>


                <div class="forecast-wrapper">


                    <table class="forecast-table">


                        <thead>

                            <tr>

                                <th>
                                    الوقت
                                </th>

                                <th>
                                    الحرارة
                                </th>

                                <th>
                                    احتمال الصقيع
                                </th>

                                <th>
                                    الحالة
                                </th>

                            </tr>

                        </thead>


                        <tbody>

                            {hours_html}

                        </tbody>


                    </table>


                </div>


            </div>


        </div>

        """


    except Exception as e:

        return f"""

        <div class="error-card">

            <h2>
                ❌ حدث خطأ
            </h2>

            <p>
                {str(e)}
            </p>

        </div>

        """


# ==========================================================
# 🔄 Update Areas
# ==========================================================

def update_area(governorate):

    areas = list(
        jordan_locations[
            governorate
        ].keys()
    )

    return gr.Dropdown(

        choices=areas,

        value=areas[0],

        label="📍 المنطقة"

    )


# ==========================================================
# 🎨 CSS
# ==========================================================

css = """

/* ======================================================
   Main Page
   ====================================================== */

.gradio-container {

    max-width:1000px !important;

    margin:auto !important;

    background:
        linear-gradient(
            135deg,
            #052e16 0%,
            #14532d 45%,
            #166534 100%
        ) !important;

    min-height:100vh;
}


body {

    background:#052e16 !important;

}


/* ======================================================
   Header
   ====================================================== */

.header {

    background:
        linear-gradient(
            135deg,
            #166534,
            #15803d
        );

    color:white;

    text-align:center;

    padding:30px;

    border-radius:
        0 0 25px 25px;

    margin-bottom:25px;
}


.header h1 {

    font-size:34px !important;

}


/* ======================================================
   Location Box
   ====================================================== */

.location-box {

    background:white !important;

    padding:25px;

    border-radius:20px;

    border:
        2px solid #22c55e !important;
}


/* ======================================================
   Check Button
   ====================================================== */

#check-button {

    background:#f25c05 !important;

    color:white !important;

    border:none !important;

    height:58px;

    border-radius:12px;

    font-size:20px !important;

    font-weight:bold;
}


/* ======================================================
   Result Card
   ====================================================== */

.result-card {

    background:#ffffff !important;

    color:#172033 !important;

    padding:30px;

    border-radius:22px;

    margin-top:20px;

    direction:rtl;

    text-align:right;

    font-family:Arial,sans-serif;

    box-shadow:
        0 8px 30px rgba(0,0,0,0.15);
}


/* ======================================================
   Title
   ====================================================== */

.result-title {

    color:#166534 !important;

    text-align:center;

    font-size:30px;

    margin-bottom:10px;
}


.green-line {

    border:0;

    border-top:
        2px solid #22c55e;

    margin:20px 0;
}


/* ======================================================
   Information
   ====================================================== */

.info-section {

    margin-top:25px;
}


.info-label {

    color:#64748b !important;

    font-size:17px;

    margin-bottom:5px;
}


.info-value {

    color:#111827 !important;

    font-size:25px;

    font-weight:bold;
}


.crop-value {

    color:#166534 !important;
}


.temperature-value {

    color:#111827 !important;

    font-size:35px;

    font-weight:bold;
}


/* ======================================================
   Risk Badge
   ====================================================== */

.risk-badge {

    display:inline-block;

    margin-top:8px;

    padding:10px 25px;

    border-radius:30px;

    font-size:23px;

    font-weight:bold;

    border:1px solid;
}


/* ======================================================
   Risk Period
   ====================================================== */

.risk-period {

    color:#111827 !important;

    font-size:20px;

    font-weight:bold;

    margin-top:8px;
}


/* ======================================================
   Recommendations
   ====================================================== */

.recommendation {

    margin-top:30px;

    padding:20px;

    border-radius:15px;

    color:#334155 !important;

    font-size:18px;

    line-height:2;
}


.recommendation,
.recommendation p,
.recommendation ul,
.recommendation li,
.recommendation span {

    color:#334155 !important;
}


.recommendation b {

    color:#166534 !important;

    font-size:20px;
}


.recommendation li {

    margin-bottom:8px;
}


/* ======================================================
   Forecast
   ====================================================== */

.forecast-section {

    margin-top:35px;
}


.forecast-title {

    color:#166534 !important;

    font-size:23px;

    margin-bottom:15px;
}


.forecast-wrapper {

    overflow-x:auto;

    width:100%;
}


.forecast-table {

    width:100%;

    border-collapse:collapse;

    text-align:center;

    direction:rtl;

    background:#ffffff !important;

    border-radius:12px;

    overflow:hidden;

    font-size:16px;
}


.forecast-table th {

    color:#ffffff !important;

    background:#166534 !important;

    font-weight:bold !important;

    padding:13px !important;

    border:
        1px solid #ffffff !important;
}


.forecast-table td {

    color:#111827 !important;

    background:#ffffff !important;

    font-weight:600 !important;

    padding:13px !important;

    border-bottom:
        1px solid #d1d5db !important;
}


.forecast-table td * {

    color:#111827 !important;
}


/* ======================================================
   Error
   ====================================================== */

.error-card {

    background:#fee2e2 !important;

    color:#991b1b !important;

    padding:25px;

    border-radius:15px;

    direction:rtl;

    text-align:right;

    margin-top:20px;
}


.error-card h2,
.error-card p {

    color:#991b1b !important;

}

"""


# ==========================================================
# 🚀 Gradio App
# ==========================================================

with gr.Blocks(

    title="🇯🇴 نظام الإنذار المبكر لخطر الصقيع",

    css=css

) as app:


    # ======================================================
    # Header
    # ======================================================

    gr.HTML("""

    <div class="header">

        <h1>
            🇯🇴 نظام الإنذار المبكر لخطر الصقيع
        </h1>

        <p>
            نظام ذكي للتنبؤ بخطر الصقيع في الأردن
        </p>

        <p>
            اختر موقعك في الأردن للحصول على تقييم خطر الصقيع
            بناءً على بيانات الطقس والنموذج التنبؤي.
        </p>

    </div>

    """)


    # ======================================================
    # Location Box
    # ======================================================

    with gr.Column(
        elem_classes="location-box"
    ):


        # --------------------------------------------------
        # Location Header
        # --------------------------------------------------

        gr.HTML("""

        <div style="

            direction:rtl;

            text-align:right;

            padding-bottom:15px;

            margin-bottom:20px;

            border-bottom:
                3px solid #22c55e;

        ">


            <h2 style="

                color:#166534 !important;

                margin:
                    0 0 8px 0;

                font-size:26px;

                font-weight:700;

            ">

                📍 اختر موقعك

            </h2>


            <p style="

                color:#475569 !important;

                margin:0;

                font-size:16px;

                font-weight:500;

            ">

                حدد المحافظة والمنطقة للحصول على نتيجة مخصصة لموقعك.

            </p>


        </div>

        """)


        # --------------------------------------------------
        # Governorate + Area
        # --------------------------------------------------

        with gr.Row():


            governorate = gr.Dropdown(

                choices=list(
                    jordan_locations.keys()
                ),

                value="عمّان",

                label="📍 المحافظة"

            )


            area = gr.Dropdown(

                choices=list(
                    jordan_locations[
                        "عمّان"
                    ].keys()
                ),

                value="عمّان",

                label="📍 المنطقة"

            )


        # --------------------------------------------------
        # Crop
        # --------------------------------------------------

        crop = gr.Dropdown(

            choices=list(
                crop_types.keys()
            ),

            value="🥬 خضروات ورقية",

            label="🌱 نوع المحصول"

        )


        # --------------------------------------------------
        # Button
        # --------------------------------------------------

        check_button = gr.Button(

            "🔍 افحص خطر الصقيع",

            elem_id="check-button"

        )


    # ======================================================
    # Result
    # ======================================================

    result = gr.HTML()


    # ======================================================
    # Governorate Change
    # ======================================================

    governorate.change(

        fn=update_area,

        inputs=governorate,

        outputs=area

    )


    # ======================================================
    # Frost Check
    # ======================================================

    check_button.click(

        fn=predict_frost_final,

        inputs=[
            governorate,
            area,
            crop
        ],

        outputs=result

    )


# ==========================================================
# 🚀 Launch
# ==========================================================

app.launch(
    share=True
)

import joblib

joblib.dump(model, "frost_random_forest.pkl")

model_info = {
    "features": features,
    "threshold": 0.20
}

joblib.dump(model_info, "frost_model_info.pkl")

print("تم حفظ الملفين ✅")